# Información de la aplicación
info:
#  app:
 #   encoding: '@project.build.sourceEncoding@' # Codificación del proyecto, típicamente UTF-8
  #java:
   # source: '@java.version@'  # Versión de Java utilizada
    #target: '@java.version@'  # Versión objetivo de Java para la compilación
  #app:
   # version: '@project.version@'  # Versión de la aplicación
    #name: '@project.name@'  # Nombre de la aplicación

spring:
  application:
    name: 'Api-productos'  # Nombre de la aplicación


main:
  banner-mode: ''
  datasource:
    url: jdbc:mysql://localhost:3306/test-db        # URL JDBC de la base de datos
    username: sd                                    # Usuario de la base de datos
    password: 123                                   # Contraseña de la base de datos
    driver-class-name: com.mysql.cj.jdbc.Driver     # Clase del controlador JDBC de MySQL
    initialization-mode: always                     # Siempre inicializa la base de datos con los scripts




  jpa:
    show-sql: true                                  # Muestra las sentencias SQL en la consola
    open-in-view: false                             # Desactiva Open Session in View para evitar problemas de lazy loading
    hibernate:
      ddl-auto: update                              # Actualiza el esquema de la base de datos automáticamente


    sql:
      init:
        mode: always                                # Siempre inicializa la base de datos con los scripts
      platform: mysql                               # Especifica la plataforma de la base de datos
      schema-locations: classpath:schema.sql        # Ruta al script de creación de esquema
      data-locations: classpath:data.sql            # Ruta al script de datos de ejemplo





doc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true


server:
  port: 8080                                        # Puerto en el que se ejecutará el servidor
  compression:
    enabled: true                                   # Habilita la compresión de las respuestas HTTP



user:
  timezone: 'UTC'                                   # Establece la zona horaria predeterminada de la aplicación



logging:
  config: classpath:log4j2.xml                       # Ruta al archivo de configuración de Log4j2
