



CREATE TABLE IF NOT EXISTS producto (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
precio VARCHAR(255) NOT NULL,
descripcion VARCHAR(255) NOT NULL,
cantidad_en_stock VARCHAR(255) NOT NULL,
categoria VARCHAR(255) NOT NULL UNIQUE,
is_active BIT DEFAULT TRUE NOT NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME NOT NULL,
version INT DEFAULT 0 NOT NULL
);
